### ISSUE TITLE
Features - loginWithCompletion / Verify

### ISSUE THREAD

**Issue by stephan-fischer** [alexziskind1/nativescript-oauth2#16]
Hello,

for the function `loginWithCompletion` is it important to get the response for some oauth like instagram e.g. to get the user data object.

And how can i check, on app start if is the user has registered the app like with a verification?

Thank you!

**Comment by alexziskind1** [comment]
I am not sure if your question is about Instagram login or getting a response back in general. Instagram doesn't currently have a provider, so that needs to be implemented. The login function does return a result with the access token and sometimes ID token. You'll need to query the related API in order to fetch more user data.
